USE WINAPI_HANDBOOK;

# DROP TABLE IF EXISTS WINAPI_CLASS ;
# DROP TABLE IF EXISTS WINAPI_FUNCTION;
# DROP TABLE IF EXISTS WINAPI_PARAMETER;

CREATE TABLE WINAPI_CLASS (
  ID          BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME        CHAR(30)      NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL
);

CREATE UNIQUE INDEX CLASSX
  ON WINAPI_CLASS (ID);

CREATE TABLE WINAPI_FUNCTION (
  ID          BIGINT        NOT NULL PRIMARY KEY AUTO_INCREMENT,
  NAME        CHAR(30)      NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  CLASS_ID    BIGINT,
  FOREIGN KEY (CLASS_ID)
  REFERENCES WINAPI_CLASS (ID)
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX FUNCTIONX
  ON WINAPI_FUNCTION (ID);

CREATE TABLE WINAPI_PARAMETER (
  ID          BIGINT   NOT NULL PRIMARY KEY AUTO_INCREMENT,
  TYPE        CHAR(30) NOT NULL,
  NAME        CHAR(30) NOT NULL,
  FUNCTION_ID BIGINT,
  FOREIGN KEY (FUNCTION_ID) REFERENCES WINAPI_FUNCTION (ID)
    ON DELETE CASCADE
);

CREATE UNIQUE INDEX PARAMX
  ON WINAPI_PARAMETER (ID);