package common.service;

import common.exception.HandbookException;
import model.WinApiClass;
import model.WinApiFunction;
import model.WinApiParameter;

import java.util.List;

public interface WinApiHandbookService {

    /**
     * Find class instance by id
     *
     * @param id class id
     * @return founded instance
     * @throws HandbookException if instance was not founded or else errors
     */
    WinApiClass getWinApiClass(long id) throws HandbookException;

    /**
     * Find classes by part of their name
     *
     * @param keyword part of name
     * @return list of founded classes
     * @throws HandbookException
     */
    List<WinApiClass> findClasses(String keyword) throws HandbookException;

    /**
     * Save class instance
     *
     * @param topic
     * @return return saved instance with all autogenerated fields
     * @throws HandbookException
     */
    WinApiClass createWinApiClass(WinApiClass topic) throws HandbookException;

    /**
     * Update existence class
     *
     * @param topic
     * @throws HandbookException if class was not updated
     */
    void updateClass(WinApiClass topic) throws HandbookException;

    /**
     * Remove existence class and all nested instances
     *
     * @param id
     * @throws HandbookException if class was not removed
     */
    void removeTopic(long id) throws HandbookException;

    /**
     * Update existence function
     *
     * @param function
     * @throws HandbookException if function was not updated
     */
    void updateWinApiFunction(WinApiFunction function) throws HandbookException;

    /**
     * Remove existence function and all nested instances
     *
     * @param id
     * @throws HandbookException if function was not removed
     */
    void removeWinApiFunction(long id) throws HandbookException;

    /**
     * Update existence function
     *
     * @param parameter
     * @throws HandbookException if function was not updated
     */
    void updateWinApiParameter(WinApiParameter parameter) throws HandbookException;

    /**
     * Remove existence parameter and all nested instances
     *
     * @param id
     * @throws HandbookException if parameter was not removed
     */
    void removeWinApiParameter(long id) throws HandbookException;
}
